name: Deploy Node.js to Digital Ocean

env:
  PATH: '/var/www/quote'
  SCRIPT: 'app.js'
  NAME: 'quote'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug information
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build --if-present
    - name: Create deployment package
      run: |
        tar --exclude='.git' --exclude='.github' --exclude='node_modules' -czf deploy.tar.gz .
    
    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD }}
        HOST: ${{ secrets.HOST }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no deploy.tar.gz ${{ secrets.SERVER_USERNAME }}@$HOST:/tmp/
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@$HOST << EOF
          rm -rf ${{ env.PATH }}
          mkdir -p ${{ env.PATH }}
          tar -xzf /tmp/deploy.tar.gz -C ${{ env.PATH }}
          rm /tmp/deploy.tar.gz
          cd ${{ env.PATH }}
          npm install --production
          pm2 restart ${{ env.NAME }} || pm2 start ${{ env.PATH }}${{ env.SCRIPT }} --name ${{ env.NAME }}
          sudo systemctl restart nginx
        EOF
    
    - name: Install sshpass
      run: sudo apt-get install sshpass

