name: Deploy Node.js to Digital Ocean

env:
  #PATH: '/var/www/quote'
  SCRIPT: 'app.js'
  NAME: 'quote'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug information
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la

